name = "DocumenterPages"
uuid = "3b6f6c89-491e-49ab-a70c-af796c43d097"
authors = ["Anshul Singhvi <anshulsinghvi@gmail.com> and contributors"]
version = "0.1.0-DEV"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
AbstractTrees = "0.4.5"
Documenter = "1.8.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
